services:
  api:
    container_name: rda-api
    build:
      dockerfile: ./docker/Dockerfile
    volumes:
        - .:/var/www/html
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - '13000:8080'

  mariadb:
    image: 'mariadb:11.4.13-ubi9'
    container_name: rda-mariadb
    environment:
        MARIADB_ROOT_PASSWORD: 'root'
    ports:
      - '13010:3306'

  redis:
    image: 'redis:latest'
    container_name: rda-redis-cache
    ports:
      - '13011:6379'
